name: Edapt
favicon: null
layout_spectrum: 0.30932384659536183
typography_spectrum: 0.09780509257689118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.06831864290870726
  lightness: 0.3216659426689148
  saturation: 0.6258637153077871
  rhythmicContrast: 0.3288142974488437
purpose: []
